name: Events Demo 1
on:
  pull_request:
    types:
    - opened
    branches:
      - main #main
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feat/new/button
    paths-ignore:
      - '.github/workflows/*'
  jobs:
  
