name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  test:
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Get Code -checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Output information
        run: |
          echo "QA var: ${{ var.QA_VARS }}"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code -checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    environment: prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Output information
        run: |
          echo "Global var: ${{ var.GLOBAL }}"
      - name: Output information env
        run: |
          echo "PROD var: ${{ var.PROD_VARS }}"
        
